java_library(
    name = "junit",
    exports = [
        "//external:jar/junit/junit"
    ],
    runtime_deps = [
        "//dependencies/artifacts/org/hamcrest:hamcrest-core"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


