java_library(
    name = "junit-repeat-rule",
    exports = [
        "//external:jar/com/github/cbismuth/junit-repeat-rule"
    ],
    runtime_deps = [
        "//dependencies/artifacts/junit:junit"
    ],
    visibility = [
        "//visibility:public"
    ]
)


